
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/parcial?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

springdoc:
  swagger-ui:operations-sorter: alpha

twilio:
  account_sid: AC898ebec06a5d80f533ccf6cbcf7bafed
  auth_token: 773c3ecab03c72c40aa2e0b7a7ae5e7a
  trial_number: +12184767322